name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t abc:latest .
        docker login -u ${{ secrets.Ananya240701 }} -p ${{ secrets.Y.48aM*/GhD_StC }}
        docker push abc:latest

    - name: Deploy to production (Replace with your deployment steps)
      run: |
        # Add deployment steps here, e.g., deploying to a server or Kubernetes cluster
